force-app/main/default/objects/Pizza__c/Pizza__c.object-meta.xml
<CustomObject>
    <description>A Pizza that is sold by the company.</description>
    <label>Pizza</label>
    <nameField>
        <displayFormat>Pizza {000} {MM}/{DD}/{YYYY}</displayFormat>
        <label>Pizza Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizzas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pizza__c/fields/isFinished__c.field-meta.xml
<CustomField>
    <fullName>isFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the pizza is ready to be delivered to the customer, unchecked if the pizza is still being made</description>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The shopping cart that this pizza belongs to.</description>
    <label>Shopping Cart</label>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>Pizzas</relationshipLabel>
    <relationshipName>Pizzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The size of the pizza</description>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra_Large</fullName>
                <label>Extra Large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepporoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <description>A virtual shopping list that contains all of the products a customer is ordering.</description>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>Cart {0000}</displayFormat>
        <label>Shopping Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the account that owns the shopping cart.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shopping Carts</relationshipLabel>
    <relationshipName>Shopping_Cart</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shopping_Cart__c/fields/Order_is_Ready__c.field-meta.xml
<CustomField>
    <fullName>Order_is_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box is checked when every pizza in the cart is finished.</description>
    <label>Order is Ready</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestOrderIsReady.cls
@isTest
public class TestOrderIsReady {
    
    static void setup(){
        list<pizza__c> testPizzas = new List<pizza__c>();
        Account testAccount = new Account(name = 'test account');
        shopping_cart__c testCart = new Shopping_Cart__c(Account__c = testAccount.ID); 
        for (Integer i = 0; i < 10; i++){
            testPizzas.add(new Pizza__c(shopping_cart__c = testCart.id, size__c = TestAutoPriceChange.SizeHelper(math.mod(i,4)), toppings__c = TestAutoPriceChange.ToppingsHelper(math.mod(i,2)), recordTypeID = TestAutoPriceChange.specialHelper(math.mod(i, 8))));
        }
        for (Pizza__c curr : testPizzas){
            if (curr.RecordTypeID == '0125e000000uuaAAAQ'){
                curr.toppings__c = TestAutoPriceChange.ToppingsHelper(500);
            }
        }
        insert testAccount;
        insert testCart;
        insert testPizzas;
    }

    @isTest
    static void testOrderIsReady(){
        setup();
        list<shopping_cart__c> carts = [SELECT id, Order_is_Ready__c FROM shopping_cart__c];
        list<pizza__c> pizzas = [SELECT id, isFinished__c, shopping_cart__c FROM pizza__c];
        //At this point, the order should not be ready.
        System.assertEquals(carts[0].Order_is_Ready__c, false);
        //Adds another pizza not in pizzas to the cart.
        Pizza__c newPizza = new Pizza__c(size__c = 'Small', shopping_cart__c = carts[0].id);
        insert newPizza;
        for (Pizza__c currPizza : pizzas){
            currPizza.isFinished__c = true;
        }
        update pizzas;
        //at this point, all but one pizza in the cart is finished - however, the new one we inserted is not.
        carts = [SELECT id, Order_is_Ready__c FROM shopping_cart__c];
        System.assertEquals(carts[0].Order_is_Ready__c, false);
        newPizza.isFinished__c = true;
        update newPizza;
        pizzas = [SELECT id, isFinished__c, shopping_cart__c FROM pizza__c];
        for (pizza__c curr : pizzas){
            System.assert(curr.isFinished__c);
        }
        carts = [SELECT id, Order_is_Ready__c FROM shopping_cart__c];
        //At this point, every pizza in the cart is finished, so the cart should be updated.
        System.assertEquals(carts[0].Order_is_Ready__c, true);

    }

}