force-app/main/default/objects/Pizza__c/Pizza__c.object-meta.xml
<CustomObject>
    <description>A Pizza that is sold by the company.</description>
    <label>Pizza</label>
    <nameField>
        <displayFormat>Pizza {000} {MM}/{DD}/{YYYY}</displayFormat>
        <label>Pizza Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizzas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pizza__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The shopping cart that this pizza belongs to.</description>
    <label>Shopping Cart</label>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>Pizzas</relationshipLabel>
    <relationshipName>Pizzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The size of the pizza</description>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra_Large</fullName>
                <label>Extra Large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepporoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/recordTypes/meatLoverSpecial.recordType-meta.xml
<RecordType>
    <fullName>meatLoverSpecial</fullName>
    <active>true</active>
    <description>A special pizza which is eligible for a discount but must be extra large and can only contain meat toppings.</description>
    <label>Meat Lover&apos;s Special</label>
</RecordType>

force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <description>A virtual shopping list that contains all of the products a customer is ordering.</description>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>Cart {0000}</displayFormat>
        <label>Shopping Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopping_Cart__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the account that owns the shopping cart.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shopping Carts</relationshipLabel>
    <relationshipName>Shopping_Cart</relationshipName>
    <type>Lookup</type>
</CustomField>

JoshSite/main/default/objects/Shopping_Cart__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sum of the cost of all items contained in the shopping cart</description>
    <label>Total Cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestCartPriceUpdate.cls
@isTest
public class TestCartPriceUpdate {
        
    static void setup(){
        list<pizza__c> testPizzas = new List<pizza__c>();
        Account testAccount = new Account(name = 'test account');
        shopping_cart__c testCart = new Shopping_Cart__c(Account__c = testAccount.ID); 
        for (Integer i = 0; i < 10; i++){
            testPizzas.add(new Pizza__c(shopping_cart__c = testCart.id, size__c = TestAutoPriceChange.SizeHelper(math.mod(i,4)), toppings__c = TestAutoPriceChange.ToppingsHelper(math.mod(i,2)), recordTypeID = TestAutoPriceChange.specialHelper(math.mod(i, 8))));
        }
        for (Pizza__c curr : testPizzas){
            if (curr.RecordTypeID == Schema.SObjectType.Pizza__C.GetRecordTypeInfosByDeveloperName().get('meatLoverSpecial').getRecordTypeID()){
                curr.toppings__c = TestAutoPriceChange.ToppingsHelper(500);
            }
        }
        insert testAccount;
        insert testCart;
        insert testPizzas;
    }
    @isTest
    static void testTotalCostUpdate(){
        Test.startTest();
        setup();
        list<shopping_cart__c> carts = [SELECT id, total_cost__c FROM shopping_cart__c];
        Decimal startCost = carts[0].total_cost__c;
        //Inserting new pizza into cart, price $14
        Pizza__c testPizza = new Pizza__c(shopping_cart__c = carts[0].id, size__c = 'Medium');
        insert testPizza;
        carts = [SELECT id, total_cost__c FROM shopping_cart__c];
        //Testing if cart price works on pizza inserts
        System.assertEquals(startCost+14, carts[0].total_cost__c);
        //Updating pizza to large, price $16
        testPizza.size__c = 'Large';
        update testPizza;
        carts = [SELECT id, total_cost__c FROM shopping_cart__c];
        //Testing if cart price works on pizza updates
        System.assertEquals(startCost+16, carts[0].total_cost__c);
        //Deleting pizza from cart, price $16
        delete testPizza;
        carts = [SELECT id, total_cost__c FROM shopping_cart__c];
        //Testing if cart price works on pizza deletions
        System.assertEquals(startCost, carts[0].total_cost__c);
        //Undeleting pizza from cart, price $16
        undelete testPizza;
        carts = [SELECT id, total_cost__c FROM shopping_cart__c];
        //Testing if cart price works on pizza undeletions
        System.assertEquals(startCost+16, carts[0].total_cost__c);
        Test.stopTest();
    }
}