force-app/main/default/objects/Pizza__c/Pizza__c.object-meta.xml
<CustomObject>
    <description>A Pizza that is sold by the company.</description>
    <label>Pizza</label>
    <nameField>
        <displayFormat>Pizza {000} {MM}/{DD}/{YYYY}</displayFormat>
        <label>Pizza Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizzas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pizza__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The shopping cart that this pizza belongs to.</description>
    <label>Shopping Cart</label>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>Pizzas</relationshipLabel>
    <relationshipName>Pizzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The size of the pizza</description>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra_Large</fullName>
                <label>Extra Large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepporoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/recordTypes/Custom_Order.recordType-meta.xml
<RecordType>
    <fullName>Custom_Order</fullName>
    <active>true</active>
    <description>A pizza which was designed by the customer</description>
    <label>Custom Order</label>
</RecordType>

force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <description>A virtual shopping list that contains all of the products a customer is ordering.</description>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>Cart {0000}</displayFormat>
        <label>Shopping Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestCreatePizzaPageExtension.cls
@isTest
public class TestCreatePizzaPageExtension {
    
    @TestSetup
    static void setup(){
        User u = new User();
        u.LastName = 'Inv #';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = 'adsnhefwuh@hdfhjfhj.com';
        u.CommunityNickname = 'test12';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileID = [SELECT id FROM Profile WHERE name = 'System Administrator' LIMIT 1].id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.IsActive = true; 
        u.UserRoleID = [SELECT id FROM UserRole WHERE name = 'CEO' LIMIT 1].id;
        u.street = 'street';
        u.city = 'city';
        u.state = 'state';
        u.postalCode = '0';
        Insert u;
    }

    @isTest
    static void testPage(){
        Test.startTest();

        User u = [SELECT id FROM User WHERE LastName = 'Inv #'  LIMIT 1];
        Shopping_Cart__C testCart = new Shopping_Cart__C(OwnerID = u.id);
        insert testCart;

        System.runAs(u){
            Pizza__C pizza = new Pizza__C(size__c = 'Medium', Shopping_Cart__c = testCart.id, recordTypeID = Schema.SObjectType.Pizza__C.GetRecordTypeInfosByDeveloperName().get('Custom_Order').getRecordTypeID());
            insert pizza;
            ApexPages.StandardController testcont = new ApexPages.StandardController(Pizza);
            CreatePizzaPageExtension ext = new CreatePizzaPageExtension(testcont);
            ext.pizza.size__c = 'Medium';
            System.assertEquals(pizza.recordTypeID, Schema.SObjectType.Pizza__C.GetRecordTypeInfosByDeveloperName().get('Custom_Order').getRecordTypeID());
            ext.pizza.toppings__c = 'Sausage';
            //Testing pizza price check
            System.assertEquals(ext.getCurrPrice(), '' + 14.50);
            //Testing page references
            System.assertEquals(ext.toCheckout().getURL(), Page.checkout.getURL());
            //Testing getPizzaIMG
            System.assertEquals(ext.getPizzaIMG(), 'PizzaS.png');
            ext.pizza.toppings__c = 'Pepporoni;Bacon';
            System.assertEquals(ext.getPizzaIMG(), 'PizzaPB.png');
            //Testing savePizza
            //ext.savePizza();
            List<Pizza__C> Pizzas = [SELECT id FROM Pizza__C];
            System.assertEquals(pizzas[0].id, ext.pizza.id);
        }
    }
}