JoshSite/main/default/objects/Order_Ticket__c/Order_Ticket__c.object-meta.xml
<CustomObject>
    <description>A junction between a user who cooks the food and the food that they are assigned to cook.</description>
    <label>Order Ticket</label>
    <nameField>
        <displayFormat>Ticket {000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Ticket__c/fields/Cook__c.field-meta.xml
<CustomField>
    <fullName>Cook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>One of the cooks in charge of making the pizza.</description>
    <label>Cook</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Ticket__c/fields/Pizza__c.field-meta.xml
<CustomField>
    <fullName>Pizza__c</fullName>
    <description>The pizza that is being made.</description>
    <label>Pizza</label>
    <referenceTo>Pizza__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pizza__c/Pizza__c.object-meta.xml
<CustomObject>
    <description>A Pizza that is sold by the company.</description>
    <label>Pizza</label>
    <nameField>
        <displayFormat>Pizza {000} {MM}/{DD}/{YYYY}</displayFormat>
        <label>Pizza Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pizzas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pizza__c/fields/isFinished__c.field-meta.xml
<CustomField>
    <fullName>isFinished__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked if the pizza is ready to be delivered to the customer, unchecked if the pizza is still being made</description>
    <label>Finished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>999.99</defaultValue>
    <description>The price of the pizza in USD - generated automatically</description>
    <label>Price USD</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Shopping_Cart__c.field-meta.xml
<CustomField>
    <fullName>Shopping_Cart__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The shopping cart that this pizza belongs to.</description>
    <label>Shopping Cart</label>
    <referenceTo>Shopping_Cart__c</referenceTo>
    <relationshipLabel>Pizzas</relationshipLabel>
    <relationshipName>Pizzas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>The size of the pizza</description>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra_Large</fullName>
                <label>Extra Large</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/fields/Toppings__c.field-meta.xml
<CustomField>
    <fullName>Toppings__c</fullName>
    <description>The toppings of the pizza - select all that apply.</description>
    <label>Toppings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pepporoni</fullName>
            </value>
            <value>
                <fullName>Bacon</fullName>
            </value>
            <value>
                <fullName>Sausage</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pizza__c/recordTypes/meatLoverSpecial.recordType-meta.xml
<RecordType>
    <fullName>meatLoverSpecial</fullName>
    <active>true</active>
    <description>A special pizza which is eligible for a discount but must be extra large and can only contain meat toppings.</description>
    <label>Meat Lover&apos;s Special</label>
</RecordType>

force-app/main/default/objects/Shopping_Cart__c/Shopping_Cart__c.object-meta.xml
<CustomObject>
    <description>A virtual shopping list that contains all of the products a customer is ordering.</description>
    <label>Shopping Cart</label>
    <nameField>
        <displayFormat>Cart {0000}</displayFormat>
        <label>Shopping Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shopping_Cart__c/fields/Order_is_Ready__c.field-meta.xml
<CustomField>
    <fullName>Order_is_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This box is checked when every pizza in the cart is finished.</description>
    <label>Order is Ready</label>
    <type>Checkbox</type>
</CustomField>

JoshSite/main/default/objects/Shopping_Cart__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The sum of the cost of all items contained in the shopping cart</description>
    <label>Total Cost</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TriggerHelper.cls
public with sharing class TriggerHelper {

    //used for Order Ticket Insert to validate inputs
    public static void checkForDuplicates(list<Order_Ticket__c> triggerlist){
        List<Order_Ticket__C> Tickets = [SELECT id, Pizza__c, Cook__c FROM Order_Ticket__c];
        for (Order_Ticket__C curr : triggerlist){
            for (Order_Ticket__C tik : Tickets){
                if (tik.cook__c == curr.cook__c && tik.pizza__c == curr.pizza__c){
                    curr.addError('this is a duplicate ticket');
                }
            }
        }
    }
    //Sets cart total cost to 0 upon creation and sets order is ready to false
    public static void setCostToZero(list<Shopping_Cart__c> triggerlist){
        for (shopping_cart__c cart : triggerlist){
            cart.Total_Cost__c = 0;
            cart.Order_is_Ready__c = false;
        }
    }
    
    // used to update the price based on the size and toppings of the pizza
    public static void updatePrice(list<pizza__c> triggerlist){
        for (pizza__c toAdjust : triggerlist){

            toAdjust.Price__c = 0.00;

            switch on toAdjust.size__c {
                when 'Small' {
                    toAdjust.price__c += 10;
                }
                when 'Medium' {
                    toAdjust.price__c += 14;
                }
                when 'Large' {
                    toAdjust.price__c += 16;
                }
                when 'Extra_Large' {
                    toAdjust.price__c += 18;
                }
            }
            if (!(toAdjust.toppings__c == null)){
                if (toAdjust.toppings__c.contains('Pepporoni')){
                    toAdjust.price__c += .50;
                }
                if (toAdjust.toppings__c.contains('Bacon')){
                    toAdjust.price__c += .50;
                }
                if (toAdjust.toppings__c.contains('Sausage')){
                    toAdjust.price__c += .50;
                }
                if (toAdjust.toppings__c.contains('Pineapple')){
                    toAdjust.price__c += .50;
                }
            }
            //Discounts based on record type (special offers)
            
            String recordType = toAdjust.RecordTypeID;
            if (recordType == Schema.SObjectType.Pizza__C.GetRecordTypeInfosByDeveloperName().get('meatLoverSpecial').getRecordTypeID()){
                toAdjust.price__c *= .80;
            }
            
        }
    }

    //Updates the price total of a shopping cart on pizza creation or update
    public static void updateShoppingCart(list<pizza__c> triggerlist, map<ID, pizza__c> triggermap){
        Map<ID, Decimal> pricedifferences = new Map<ID, Decimal>();
        for (pizza__c toAdjust : triggerlist){
            if (Trigger.isInsert || Trigger.isUndelete){
                pricedifferences.put(toAdjust.shopping_cart__c, toAdjust.price__c);
            } else if (Trigger.isDelete){
                pricedifferences.put(toAdjust.shopping_cart__c, (toAdjust.price__c * -1));
            } else {
                if (toAdjust.price__c != triggermap.get(toAdjust.id).price__c){
                    pricedifferences.put(toAdjust.shopping_cart__c, toAdjust.price__c - triggermap.get(toAdjust.id).price__c);
                }
            }
        }
        List<shopping_cart__c> cartList = [SELECT id, total_cost__c FROM Shopping_cart__c];
        for (shopping_cart__c toAdjust: cartList){
            if (!(pricedifferences.get(toAdjust.id) == null)){
                toAdjust.Total_Cost__c += pricedifferences.get(toAdjust.id);
            }
        }
        Update cartList;
    }

    //Updates shopping cart's "Order_is_Ready__c" field based on whether or not all of the pizzas in it is finished.

    public static void checkIfOrderIsReady(list<pizza__c> triggerlist){

        List<Pizza__C> pizzaList = [SELECT id, isFinished__c, shopping_cart__c FROM Pizza__C];
        List<shopping_cart__c> cartList = [SELECT id, Order_is_Ready__c FROM Shopping_cart__c];
        //Carts are updated to all be ready;
        for (Shopping_Cart__c currCart : cartList){
            currCart.Order_is_Ready__c = true;
        }
        List<Shopping_cart__c> notReady = new List<Shopping_cart__c>();
        //Carts are removed from cartList if any of their pizzas is not ready
        for (Pizza__c currPizza : pizzaList){
            for (Shopping_cart__c currCart : cartList){
                if ((currPizza.shopping_cart__c == currCart.id) && !currPizza.isFinished__c){
                    notReady.add(currCart);
                }
            }
        }
        for (shopping_cart__c currCart : notReady){
            if (cartList.indexOf(currCart) != -1){
                cartList.remove(cartList.indexOf(currCart));
            }
        }

        update cartList;

    }
}