force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>To store the job applications</description>
    <label>Application</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Details of the applicants</description>
    <inlineHelpText>Enter your personal details relevant to job</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <inlineHelpText>Enter your First Name</inlineHelpText>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <description>Contains jobs listing</description>
    <label>Career</label>
    <nameField>
        <label>Career Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Careers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SubmitApplication.cls
public class SubmitApplication {
   
    public Application__c appFile;
	public final Career__c acct; 
    // constructor is for job list page
    public SubmitApplication(ApexPages.StandardSetController controller) {}
    // constructor for application page
    public SubmitApplication(ApexPages.StandardController controller){
        appFile = (Application__c)controller.getRecord();
    }

    public transient Attachment myDocument;
    public Attachment myDoc{
        get{
            if(myDocument==null){
                myDocument = new Attachment();
            }
            return myDocument;
        }
        set;
    }

    public PageReference upload(){
        Application__c newApp = new Application__c(); 
        newApp.First_Name__c = appFile.First_Name__c;
        newApp.Last_Name__c = appFile.Last_Name__c;
        newApp.Phone__c = appFile.Phone__c;
        newApp.Email__c = appFile.Email__c;
        newApp.Details__c = appFile.Details__c;
        try {
            Insert newApp; 
            myDoc.parentId = newApp.Id;
            insert myDoc; 
        } catch (DMLException e){
            ApexPages.addMessages(e);
            return null;
        } 
        ApexPages.addMessage(new ApexPages.message(Apexpages.Severity.INFO,'Application submitted!'));
        return null;
    }
        // redirect to Application page
    public PageReference applyJob() {
        PageReference pageRef = new PageReference('/apex/application');
        return pageRef;    
    }
        // redirect to FirstPage (Job Lists)
    public PageReference jobList(){
       // PageReference pageRef = new PageReference('/apex/FirstPage');
       // Changing to redirect to home page. 
        PageReference pageRef = new PageReference('https://joesfloatingpalace-developer-edition.na163.force.com/CustomerTest');
       return pageRef;    
    }
   
}